blank_issues_enabled: false
contact_links:
  - name: Foundry VTT Discord
    url: https://discord.gg/foundryvtt
    about: Join the Foundry VTT Discord for community support
  - name: DnD5e System GitHub
    url: https://github.com/foundryvtt/dnd5e
    about: Check the official DnD5e system repository for related issues
