name: Release Please

on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: foundryvtt-dnd5e-types
          token: ${{ secrets.GITHUB_TOKEN }}
          extra-files: |
            version.json
          changelog-notes-type: github
          changelog-types: |
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"docs","section":"Documentation","hidden":false},
             {"type":"chore","section":"Miscellaneous","hidden":false}]

      # The logic below handles the npm publication:
      - uses: actions/checkout@v3
        # These if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}

      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - run: npm run build
        if: ${{ steps.release.outputs.release_created }}

      - name: Get DnD5e version
        id: dnd5e-version
        run: echo "dnd5e_version=$(node -p "require('./version.json').dnd5eVersion")" >> $GITHUB_OUTPUT
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to npm
        run: npm publish --tag dnd5e-v${{ steps.dnd5e-version.outputs.dnd5e_version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}

      - name: Build documentation
        run: npm run docs
        if: ${{ steps.release.outputs.release_created }}

      - name: Update release description
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const versionInfo = JSON.parse(fs.readFileSync('./version.json', 'utf8'))
            const releaseId = ${{ steps.release.outputs.release_id }}
            const releaseData = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId
            })

            const newBody = `## Compatible with DnD5e version ${versionInfo.dnd5eVersion}\n\n${releaseData.data.body}\n\n## Installation\n\n\`\`\`bash\nnpm install --save-dev foundryvtt-dnd5e-types@${releaseData.data.tag_name}\n\`\`\`\n\nOr with a specific DnD5e version tag:\n\n\`\`\`bash\nnpm install --save-dev foundryvtt-dnd5e-types@dnd5e-v${versionInfo.dnd5eVersion}\n\`\`\`\n\n## Documentation\n\nFor full documentation, visit the [GitHub repository](https://github.com/${context.repo.owner}/${context.repo.repo})`

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              body: newBody
            })
